name: ngekoskiye
description: "Aplikasi mobile marketplace kost berbasis Flutter untuk pencarian, booking, dan manajemen transaksi kost secara online."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  dio: ^5.9.2
  go_router: ^17.2.3
  flutter_secure_storage: ^10.1.0
  google_fonts: ^8.1.0
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  image_picker: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  freezed: ^3.2.5
  json_serializable: ^6.13.2

flutter:

  uses-material-design: true
