// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Menyediakan konfigurasi Firebase untuk setiap platform yang didukung.
///
/// Class ini dipakai saat aplikasi melakukan inisialisasi Firebase.
class DefaultFirebaseOptions {
  /// Mengambil konfigurasi Firebase yang sesuai dengan platform saat ini.
  ///
  /// Nilai ini digunakan saat Firebase diinisialisasi.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3G0AdsbpVnTvAgVwFeCG3I69_F8QH14U',
    appId: '1:537398221291:web:3bd81e45674c58039c61ae',
    messagingSenderId: '537398221291',
    projectId: 'ngekoskiye-app',
    authDomain: 'ngekoskiye-app.firebaseapp.com',
    storageBucket: 'ngekoskiye-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe7YAaenrmzstCzCDKGRuSg0Z_0Ja5K84',
    appId: '1:537398221291:android:9680be97b0662b149c61ae',
    messagingSenderId: '537398221291',
    projectId: 'ngekoskiye-app',
    storageBucket: 'ngekoskiye-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEQIVpeeA-hfsx5kZTsOV_Tb_x_FwIFbw',
    appId: '1:537398221291:ios:f8921836e3a4dea99c61ae',
    messagingSenderId: '537398221291',
    projectId: 'ngekoskiye-app',
    storageBucket: 'ngekoskiye-app.firebasestorage.app',
    iosBundleId: 'com.ngekoskiye',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEQIVpeeA-hfsx5kZTsOV_Tb_x_FwIFbw',
    appId: '1:537398221291:ios:bf245871fcee12d39c61ae',
    messagingSenderId: '537398221291',
    projectId: 'ngekoskiye-app',
    storageBucket: 'ngekoskiye-app.firebasestorage.app',
    iosBundleId: 'com.ngekoskiye',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3G0AdsbpVnTvAgVwFeCG3I69_F8QH14U',
    appId: '1:537398221291:web:ca9b329d04c3ee209c61ae',
    messagingSenderId: '537398221291',
    projectId: 'ngekoskiye-app',
    authDomain: 'ngekoskiye-app.firebaseapp.com',
    storageBucket: 'ngekoskiye-app.firebasestorage.app',
  );
}